# This is an example neoforge.mods.toml file. It contains the data relating to the loading of a mod.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the neoforge version
loaderVersion = "[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "All rights reserved"

# A URL to refer people to when problems occur with this mod
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "jurassicraft" #mandatory

# The version number of the mod
version = "${file.jarVersion}" #mandatory

# A display name for the mod
displayName = "JurassiCraft" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
# updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://minecraft.curseforge.com/projects/jurassicraft" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "jurassicraft_logo.png" #optional

# A text field displayed in the mod UI
credits = "Thanks to the JurassiCraft Team and all contributors!" #optional

# A text field displayed in the mod UI
authors = "JurassiCraft Team" #optional

# Description text for the mod (multi line!) (#mandatory)
description = '''
JurassiCraft is a mod based on Jurassic Park and Jurassic World franchises, but is not only limited to it. This mod allows you to create dinosaurs by extracting DNA from fossils and amber, and putting that through a process until you get a baby dinosaur! Not only does this mod add dinosaurs, it also adds many prehistoric plants, decorations, vehicles and much more!
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.jurassicraft]] #optional
# the modid of the dependency
modId = "neoforge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[21.1,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"

# Here's another dependency
[[dependencies.jurassicraft]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to the next major version of minecraft.
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"